# Generated by Django 5.2.3 on 2025-06-25 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_otpstorage_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theatreId', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(max_length=50)),
                ('qty', models.IntegerField()),
                ('seatType', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grandTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.BigIntegerField()),
                ('mobileNumber', models.CharField(max_length=20)),
                ('eventId', models.CharField(blank=True, max_length=100, null=True)),
                ('eventName', models.CharField(blank=True, max_length=255, null=True)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('ticketType', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.user')),
            ],
        ),
    ]
