# Generated by Django 5.2.3 on 2025-06-27 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_booking_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('rating', models.FloatField()),
                ('directors', models.CharField(max_length=255)),
                ('producers', models.CharField(max_length=255)),
                ('actors', models.TextField()),
                ('cast', models.TextField()),
                ('crew', models.TextField()),
                ('reviews', models.TextField()),
                ('image', models.URLField()),
                ('language', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.user')),
            ],
        ),
    ]
